name: Release and Publish

on:
  release:
    types: [published]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-restore

    - name: Pack NuGet package
      run: dotnet pack --configuration Release --no-build --output nupkgs

    - name: Publish to NuGet
      run: |
        cd nupkgs
        for package in *.nupkg; do
          if [[ $package != *.symbols.nupkg ]]; then
            echo "Publishing $package to NuGet..."
            dotnet nuget push "$package" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
          fi
        done

    - name: Comment on release
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.payload.release.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ **ZiggyMath ${{ github.event.release.tag_name }}** has been successfully published to NuGet!\n\n📦 **Installation:**\n```bash\ndotnet add package ZiggyMath\n```\n\n🔗 **Package:** https://www.nuget.org/packages/ZiggyMath/${{ github.event.release.tag_name }}'
          })